In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
path = '/content/drive/MyDrive/Colab Notebooks/dataset/wine_data.csv'
winedata = pd.read_csv(path) ## Dataset is now stored in a Pandas Dataframe
print ("Dataset Lenght:: ", len(winedata))
print ("Dataset Shape:: ", winedata.shape)
print(winedata)

Dataset Lenght::  177
Dataset Shape::  (177, 14)
     1  14.23  1.71  2.43  15.6  127  ...   .28  2.29   5.64  1.04  3.92  1065
0    1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28   4.38  1.05  3.40  1050
1    1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81   5.68  1.03  3.17  1185
2    1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18   7.80  0.86  3.45  1480
3    1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82   4.32  1.04  2.93   735
4    1  14.20  1.76  2.45  15.2  112  ...  0.34  1.97   6.75  1.05  2.85  1450
..  ..    ...   ...   ...   ...  ...  ...   ...   ...    ...   ...   ...   ...
172  3  13.71  5.65  2.45  20.5   95  ...  0.52  1.06   7.70  0.64  1.74   740
173  3  13.40  3.91  2.48  23.0  102  ...  0.43  1.41   7.30  0.70  1.56   750
174  3  13.27  4.28  2.26  20.0  120  ...  0.43  1.35  10.20  0.59  1.56   835
175  3  13.17  2.59  2.37  20.0  120  ...  0.53  1.46   9.30  0.60  1.62   840
176  3  14.13  4.10  2.74  24.5   96  ...  0.56  1.35   9.20  0.61  1.60   560

[1

In [ ]:
features = ["Cultivator", "Alchol", "Malic_Acid", "Ash", "Alcalinity_of_Ash", "Magnesium", "Total_phenols", "Falvanoids", "Nonflavanoid_phenols", "Proanthocyanins", "Color_intensity", "Hue", "OD280", "Proline"]
winedata = pd.read_csv(path, names = features) #ถ้าถ้อ่านจาก อ่ drive ให้ให้ช้ ตัวแปร ตั path
#winedata = pd.read_csv('wine_data.csv', names = features) #้ถ้าถ้อ่านจาก อ่ local ให้ระห้ บุชื่บุ อไฟ ชื่ ล์ไล์ ด้เลย ด้
winedata.head()
X = winedata.drop('Cultivator',axis=1)
y = winedata['Cultivator']
print(X)
print(y)

     Alchol  Malic_Acid   Ash  ...   Hue  OD280  Proline
0     14.23        1.71  2.43  ...  1.04   3.92     1065
1     13.20        1.78  2.14  ...  1.05   3.40     1050
2     13.16        2.36  2.67  ...  1.03   3.17     1185
3     14.37        1.95  2.50  ...  0.86   3.45     1480
4     13.24        2.59  2.87  ...  1.04   2.93      735
..      ...         ...   ...  ...   ...    ...      ...
173   13.71        5.65  2.45  ...  0.64   1.74      740
174   13.40        3.91  2.48  ...  0.70   1.56      750
175   13.27        4.28  2.26  ...  0.59   1.56      835
176   13.17        2.59  2.37  ...  0.60   1.62      840
177   14.13        4.10  2.74  ...  0.61   1.60      560

[178 rows x 13 columns]
0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Cultivator, Length: 178, dtype: int64


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn.preprocessing import StandardScaler #สร้างออบเ ร้ จ็กต์ขึ้ต์ นจากคลาส ขึ้ StandardScaler
ss = StandardScaler() #ข้อข้มูลมู ดิบของ ดิ wine data ผ่านการ ผ่ ทํา data preprocessing แบบ StandardScale
#print(X)
X_scaled = ss.fit_transform(X)
# fit_transform ทํา การคํา นวณค่าเฉ ค่ ลี่ยและ ลี่ ส่วนเ ส่ บี่ยงเบนมาตรฐานของ บี่ ข้อข้มูลมู X และคืนคื ค่าค่ X ที่ทําที่ ทํา ให้เห้ป็นมาตรฐานแล้
print(X_scaled)

[[ 1.51861254 -0.5622498   0.23205254 ...  0.36217728  1.84791957
   1.01300893]
 [ 0.24628963 -0.49941338 -0.82799632 ...  0.40605066  1.1134493
   0.96524152]
 [ 0.19687903  0.02123125  1.10933436 ...  0.31830389  0.78858745
   1.39514818]
 ...
 [ 0.33275817  1.74474449 -0.38935541 ... -1.61212515 -1.48544548
   0.28057537]
 [ 0.20923168  0.22769377  0.01273209 ... -1.56825176 -1.40069891
   0.29649784]
 [ 1.39508604  1.58316512  1.36520822 ... -1.52437837 -1.42894777
  -0.59516041]]


In [ ]:
from sklearn import preprocessing
X_train = np.array([[ 1, -1, 2],[ 2, 0, 6],[ 0, 1, -1]])

In [ ]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
print(X_train_minmax)

[[0.5        0.         0.42857143]
 [1.         0.5        1.        ]
 [0.         1.         0.        ]]


In [ ]:
from sklearn.preprocessing import StandardScaler #สร้างออบเ ร้ จ็กต์ขึ้ต์ นจากคลาส ขึ้ StandardScaler
ss = StandardScaler() #ข้อข้มูลมู ดิบของ ดิ wine data ผ่านการ ผ่ ทํา data preprocessing แบบ StandardScale
#print(X)
X_scaled = ss.fit_transform(X_train)
# fit_transform ทํา การคํา นวณค่าเฉ ค่ ลี่ยและ ลี่ ส่วนเ ส่ บี่ยงเบนมาตรฐานของ บี่ ข้อข้มูลมู X และคืนคื ค่าค่ X ที่ทําที่ ทํา ให้เห้ป็นมาตรฐานแล้
print(X_scaled)

[[ 0.         -1.22474487 -0.11624764]
 [ 1.22474487  0.          1.27872403]
 [-1.22474487  1.22474487 -1.16247639]]


In [ ]:
df = pd.DataFrame({
    'Part': ['Monitor', 'CPU', None, 'Mouse', None, 'Extensions', 'Table', 'Chair', 'Wifi'],
    'Feature': ['LED', 'i7', 'RGB', 'Wireless', 'Zebronics', None, 'Urban Clap', 'Apex Chairs', 'Airtel'],
    'Price': [12000, 3500, None, 1200, None, 250, 7000, 12000, 799]
})
print(df)

         Part      Feature    Price
0     Monitor          LED  12000.0
1         CPU           i7   3500.0
2        None          RGB      NaN
3       Mouse     Wireless   1200.0
4        None    Zebronics      NaN
5  Extensions         None    250.0
6       Table   Urban Clap   7000.0
7       Chair  Apex Chairs  12000.0
8        Wifi       Airtel    799.0


In [ ]:
df.isnull()

Part  Feature  Price
0  False    False  False
1  False    False  False
2   True    False   True
3  False    False  False
4   True    False   True
5  False     True  False
6  False    False  False
7  False    False  False
8  False    False  False

In [ ]:
df.dropna()

Part      Feature    Price
0  Monitor          LED  12000.0
1      CPU           i7   3500.0
3    Mouse     Wireless   1200.0
6    Table   Urban Clap   7000.0
7    Chair  Apex Chairs  12000.0
8     Wifi       Airtel    799.0

In [ ]:
df

Part      Feature    Price
0     Monitor          LED  12000.0
1         CPU           i7   3500.0
2        None          RGB      NaN
3       Mouse     Wireless   1200.0
4        None    Zebronics      NaN
5  Extensions         None    250.0
6       Table   Urban Clap   7000.0
7       Chair  Apex Chairs  12000.0
8        Wifi       Airtel    799.0

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.NaN, strategy='mean')
# ถ้าถ้มีข้มี อข้มูลมู มีเมีพียงพี 1 มิติมิ ติ(Feature ที่ต้ที่ องการเป ต้ ลี่ยนลี่ มี Column เดียวดี ) ต้องต้ มีการ มี .reshape() ให้อห้ ยู่ในยู่ รูปรู 1 มิติมิ ก่ติอก่
df.Price= imputer.fit_transform(df['Price'].values.reshape(-1,1))[:,0]
df

Part      Feature         Price
0     Monitor          LED  12000.000000
1         CPU           i7   3500.000000
2        None          RGB   5249.857143
3       Mouse     Wireless   1200.000000
4        None    Zebronics   5249.857143
5  Extensions         None    250.000000
6       Table   Urban Clap   7000.000000
7       Chair  Apex Chairs  12000.000000
8        Wifi       Airtel    799.000000

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=None, strategy='most_frequent') #สังเกตตรง สั missing va
df.Feature= imputer.fit_transform(df['Feature'].values.reshape(-1,1))[:,0]
df.Part= imputer.fit_transform(df['Part'].values.reshape(-1,1))[:,0]
df

Part      Feature         Price
0     Monitor          LED  12000.000000
1         CPU           i7   3500.000000
2         CPU          RGB   5249.857143
3       Mouse     Wireless   1200.000000
4         CPU    Zebronics   5249.857143
5  Extensions       Airtel    250.000000
6       Table   Urban Clap   7000.000000
7       Chair  Apex Chairs  12000.000000
8        Wifi       Airtel    799.000000

In [ ]:
from sklearn.impute import SimpleImputer
students = [[85, 'M', 'verygood'],
[95, 'F', 'excellent'],
[75, None,'good'],
[np.NaN, 'M', 'average'],
[70, 'M', 'good'],
[np.NaN, None, 'verygood'],
[92, 'F', 'verygood'],
[98, 'M', 'excellent']]
features = ['marks', 'gender', 'result']
df = pd.DataFrame(students, columns = features )

In [ ]:
imputer = SimpleImputer(missing_values=None, strategy='most_frequent')
imputer2 = SimpleImputer(missing_values=np.NaN, strategy='mean')
df.gender= imputer.fit_transform(df['gender'].values.reshape(-1,1))[:,0]
df.marks= imputer2.fit_transform(df['marks'].values.reshape(-1,1))[:,0]
df

marks gender     result
0  85.000000      M   verygood
1  95.000000      F  excellent
2  75.000000      M       good
3  85.833333      M    average
4  70.000000      M       good
5  85.833333      M   verygood
6  92.000000      F   verygood
7  98.000000      M  excellent

In [26]:
from sklearn.preprocessing import StandardScaler 
import pandas as pd
import math 
ss = StandardScaler() 
x = [532,502,570,592,469,488,501,490,590,510]
Sum = 0
for n in range (0,10):
  Sum += (x[n]-SmaBar)**2
SD = math.sqrt(Sum/10)
Str = ' '
for i in range (0,10):
  F = (x[i]-SmaBar)/SD 
  Str += str(x[i])+ ' ---> '
  print(Str + "{:.5f}".format(F))
  Str = ' '

 532 ---> 0.17991
 502 ---> -0.53027
 570 ---> 1.07948
 592 ---> 1.60028
 469 ---> -1.31147
 488 ---> -0.86169
 501 ---> -0.55394
 490 ---> -0.81434
 590 ---> 1.55293
 510 ---> -0.34089


'print(sum(x))\nprint(SD)\nprint(x1)'